//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public Ban()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MABAN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
