//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBan
    {
        public int DatBanID { get; set; }
        public Nullable<int> BanID { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
        public string MAKH { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    
        public virtual Ban2 Ban2 { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
