//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public GiamGia()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MAGIAMGIA { get; set; }
        public string CODE { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> SOTIEN { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
