//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBNHEntities1 : DbContext
    {
        public DBNHEntities1()
            : base("name=DBNHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ban> Bans { get; set; }
        public DbSet<Ban2> Ban2 { get; set; }
        public DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public DbSet<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
        public DbSet<DanhGia> DanhGias { get; set; }
        public DbSet<DatBan> DatBans { get; set; }
        public DbSet<GiamGia> GiamGias { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<MonAn> MonAns { get; set; }
        public DbSet<NguyenLieu> NguyenLieux { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public DbSet<QuyenTruyCap> QuyenTruyCaps { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual int InsertHoaDon(string maHoaDon, string maNV, string maKH, Nullable<System.DateTime> ngayLap)
        {
            var maHoaDonParameter = maHoaDon != null ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHoaDon", maHoaDonParameter, maNVParameter, maKHParameter, ngayLapParameter);
        }
    }
}
