//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        public NguyenLieu()
        {
            this.ChiTietNhapKhoes = new HashSet<ChiTietNhapKho>();
        }
    
        public string MANGUYENLIEU { get; set; }
        public string MAKHO { get; set; }
        public string TENNGUYENLIEU { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    
        public virtual ICollection<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
    }
}
