//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
        }
    
        public string MANV { get; set; }
        public string MATAIKHOAN { get; set; }
        public string HOTEN { get; set; }
        public string SODT { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
