//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        public PhieuNhapKho()
        {
            this.ChiTietNhapKhoes = new HashSet<ChiTietNhapKho>();
        }
    
        public string MANHAPKHO { get; set; }
        public string MANV { get; set; }
        public Nullable<System.DateTime> NGAYNK { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
    
        public virtual ICollection<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
