//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_NhaHang_ADO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.KhachHangs = new HashSet<KhachHang>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MATAIKHOAN { get; set; }
        public string MAQUYEN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ISEMAILCONFIRMED { get; set; }
        public string EMAILCONFIRMATIONTOKEN { get; set; }
        public Nullable<int> OTP { get; set; }
    
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        public virtual QuyenTruyCap QuyenTruyCap { get; set; }
    }
}
